name: CI/CD

on:
  push:
    branches:
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean gretl:build gretl:publishPluginMavenPublicationToMavenLocal -x test
      - name: Publish plugin
        run: ./gradlew gretl:publishPlugins
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          gradlePublishKey: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradlePublishSecret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
